---
title: "TwoStageModelling"
author: "Wanchang Zhang"
date: "2023-03-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(GGally)
library(data.table)
#library(Hmisc)
#library(mice)
library(lattice)
library(nlme)
library(reshape2)
library(MASS)
#library(mnormt)
library(lme4)
library(gridExtra)
library(knitr)
#library(kableExtra)
library(broom)
library(tidyverse)
```
```{r}
library(readxl)
trenal <- read_excel("Trenal.XLS") # summary(trenal)
trenal= trenal[,-18] #remove a noninformative column const
# Continuous or discrete variables
trenal$id = as.factor(trenal$id)
trenal$j = as.factor(trenal$j)
#trenal$time = as.factor(trenal$time)
trenal$male = as.factor(trenal$male)
trenal$cardio = as.factor(trenal$cardio)
trenal$reject = as.factor(trenal$reject)
# Change the name of respons
colnames(trenal)[19] <- "Hc"
trenal.long = trenal[,13:20] # long table form

# Remove j
trenal.long = trenal.long[,-6]
trenal.long.unique <- trenal.long[match( unique(trenal.long$id), trenal.long$id),]
trenal.long.noNA <- na.omit(trenal.long)

# Wide table form
trenal.wide = as.data.frame(subset(trenal,trenal$j=="1"))[,1:18] # 1160 x 18
```

```{r}
set.seed(1)
selected <- sample(1:length(unique(trenal.long.noNA$id)),30,replace=T) # random samples and permutations
#selected.vector = as.vector(selected)
data.selected = trenal.long.noNA[(trenal.long.noNA$id %in% c(selected)), ] 
```




```{r}
trenal.grouped<-groupedData(Hc~time|id,trenal.long.noNA, inner = ~ male, labels=list(y="level of Haematocrit"),units=list(y="%"))
modlist1 <- lmList (Hc ~ time|id, trenal.grouped , na.action = na.pass)
a = coef(modlist1)[,1]
b = coef(modlist1)[,2]
plot.new()
par(mfrow=c(1,2))
hist(a,xlab="intercepts",ylab="Frequency",title="Histogram for intercepts")
hist(b,xlab="slopes",ylab="Frequency",title="Histogram for time slopes")

bbdd <- data.frame(id=as.numeric(attributes(modlist1)$names),
                 a=coef(modlist1)[,1],b=coef(modlist1)[,2])
bbdd <- merge(trenal.long, bbdd[,c("id","a", "b")], by.x = "id", all.x = T)

bbdd <- bbdd[order(bbdd[,1]),]
ggplot(bbdd, aes(x=a, y=b)) + geom_point() + ggtitle("Beta comparison")
(meanabymale<-tapply(bbdd$a,as.factor(bbdd$male),mean,na.rm=T))
(meanbbymale<-tapply(bbdd$b,as.factor(bbdd$male),mean,na.rm=T))
ggplot(bbdd, aes(x=a, y=b, color=male)) +
geom_point()+
  geom_smooth(method='lm', formula= y~x)+
ggtitle("Beta comparison by Gender")

```
Fit the model and confidence interval. We will use the structure found in the multivariate section. 

```{r}
### Fit a model for the intercept

fita.agemalecardio<-lm(a ~ age + male + cardio ,bbdd)
summary(fita.agemalecardio)
confint(fita.agemalecardio)

### Fit a model for the slope

fitb.agemalecardio<-lm(b~age + male + cardio ,bbdd)
summary(fitb.agemalecardio)
confint(fitb.agemalecardio)

```



```{r}
trenal.grouped<-groupedData(Hc~time|id,trenal.long.noNA, inner = ~ reject, labels=list(y="level of Haematocrit"),units=list(y="%"))
modlist1 <- lmList (Hc ~ time|id, trenal.grouped , na.action = na.pass)
bbdd <- data.frame(id=as.numeric(attributes(modlist1)$names),
                 a=coef(modlist1)[,1],b=coef(modlist1)[,2])
bbdd <- merge(trenal.long, bbdd[,c("id","a", "b")], by.x = "id", all.x = T)

bbdd <- bbdd[order(bbdd[,1]),]
ggplot(bbdd, aes(x=a, y=b)) + geom_point() + ggtitle("Beta comparison")
(meanabymale<-tapply(bbdd$a,as.factor(bbdd$reject),mean,na.rm=T))
(meanbbymale<-tapply(bbdd$b,as.factor(bbdd$reject),mean,na.rm=T))
ggplot(bbdd, aes(x=a, y=b, color=reject)) +
geom_point()+
  geom_smooth(method='lm', formula= y~x)+
ggtitle("Beta comparison by Reject")

```

```{r}
trenal.grouped<-groupedData(Hc~time|id,trenal.long.noNA, inner = ~ cardio, labels=list(y="level of Haematocrit"),units=list(y="%"))
modlist1 <- lmList (Hc ~ time|id, trenal.grouped , na.action = na.pass)
bbdd <- data.frame(id=as.numeric(attributes(modlist1)$names),
                 a=coef(modlist1)[,1],b=coef(modlist1)[,2])
bbdd <- merge(trenal.long, bbdd[,c("id","a", "b")], by.x = "id", all.x = T)

bbdd <- bbdd[order(bbdd[,1]),]
ggplot(bbdd, aes(x=a, y=b)) + geom_point() + ggtitle("Beta comparison")
(meanabymale<-tapply(bbdd$a,as.factor(bbdd$cardio),mean,na.rm=T))
(meanbbymale<-tapply(bbdd$b,as.factor(bbdd$cardio),mean,na.rm=T))
ggplot(bbdd, aes(x=a, y=b, color=cardio)) +
geom_point()+
  geom_smooth(method='lm', formula= y~x)+
ggtitle("Beta comparison by Cardio")

```













```{r}
regressions <- data.selected %>%
  group_by(id) %>%
  do(fit = lm(Hc ~ time,data=.))#,confintval = confint(fit))
  
sd_filter <- data.selected %>%
  group_by(id) %>%
  summarise(sds = sd(Hc))

regressions <- regressions %>% 
  right_join(sd_filter,by="id")%>%
  filter(!is.na(sds))

lm_info2 <- regressions %>%
  tidy(fit) %>%
  ungroup() %>%
  dplyr::select(id,terms,std.error) %>%
  spread(key = term, value = std.error)

regressions[[2]][[1]]$coefficients

lm_info1 <- regressions %>%
  tidy(fit)%>%
  ungroup() %>%
  dplyr::select(id,terms,estimate) %>%
  spread(key = term, value = estimate) %>%
  rename(rate = time,int = `(Intercept)`)

```


```{r}
trenal.grouped<-groupedData(Hc~time|id,trenal.long.noNA, inner = ~ male+cardio+reject, labels=list(y="level of Haematocrit"),units=list(y="%"))
modlist1 <- lmList (Hc ~ time|id, trenal.grouped , na.action = na.pass)
a = coef(modlist1)[,1]
b = coef(modlist1)[,2]
plot.new()
par(mfrow=c(1,2))
hist(a,xlab="intercepts",ylab="Frequency",title="Histogram for intercepts")
hist(b,xlab="slopes",ylab="Frequency",title="Histogram for time slopes")
bbdd <- data.frame(id=as.numeric(attributes(modlist1)$names),
                 a=coef(modlist1)[,1],b=coef(modlist1)[,2])
bbdd <- merge(trenal.long, bbdd[,c("id","a", "b")], by.x = "id", all.x = T)

bbdd <- bbdd[order(bbdd[,1]),]
ggplot(bbdd, aes(x=a, y=b)) + geom_point() + ggtitle("Beta comparison")
(meanabymale<-tapply(bbdd$a,as.factor(bbdd$male),mean,na.rm=T))
(meanbbymale<-tapply(bbdd$b,as.factor(bbdd$male),mean,na.rm=T))
ggplot(bbdd, aes(x=a, y=b, color=male)) +
geom_point()+
  geom_smooth(method='lm', formula= y~x)+
ggtitle("Beta comparison by Gender")

```

## Step two
Fit the model and confidence interval. We will use the structure found in the multivariate section. 


```{r}
### Fit a model for the intercept
fita<-lm(a~ age +male + cardio ,bbdd)
summary(fita)
confint(fita)

### Fit a model for the slope

fitb<-lm(b~age + male + cardio ,bbdd)
summary(fitb)
confint(fitb)

```